name = "TheoLib"
version = "0.1.0"
defaultTargets = ["TheoLib"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.29.1"

[[lean_lib]]
name = "TheoLib"

[[lean_exe]]
name = "theolib"
root = "Main"
